--CREATE USER TABLE--
CREATE TABLE tbl_USER(USER_ID INT PRIMARY KEY, FIRST_NAME VARCHAR(30), LAST_NAME VARCHAR(30), USER_NAME VARCHAR(30) NOT NULL, EMAIL_ID VARCHAR(30) NOT NULL, PHONE_NO VARCHAR(10) NOT NULL, PASSWORD VARCHAR(15) NOT NULL,CREATED_DATE DATETIME,LAST_MODIFIED DATETIME,LAST_LOGIN DATETIME);

--CREATE SEQUENCE FOR USER_ID--
CREATE SEQUENCE seq_USER_ID AS INT START WITH 1001 INCREMENT BY 1; 

--INSERTING VALUES IN USER TABLE--
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES(NEXT VALUE FOR seq_USER_ID,'HEMANTH','RAM','HEMANTH17','zerogravity72@gmail.com','9766583442','sheaman@72',GETDATE()); 
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES(NEXT VALUE FOR seq_USER_ID,'SAI','SANJEEV','SAI25','sai7225@gmail.com','9980672746','Sais$25',GETDATE()); 
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES(NEXT VALUE FOR seq_USER_ID,'BALAJI','SUNDARRAJAN','BALAJI6','balajis6332@gmail.com','9897899880','balajileads_44',GETDATE()); 
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES(NEXT VALUE FOR seq_USER_ID,'LAVANYA','RAJAGOPALAN','LAVANYA1225','lav.6522nya@gmail.com','9980352271','lavs$iscool',GETDATE()); 
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES(NEXT VALUE FOR seq_USER_ID,'PREETHI','CVV','PREETHI23','preethicvv@gmail.com','9640782444','preetz#cvv89',GETDATE()); 

--PROCEDURE TO CREATE RECORDS IN USER TABLE--
CREATE PROCEDURE proc_USER_CREATE 
@FIRST_NAME VARCHAR(30), 
@LAST_NAME VARCHAR(30), 
@USER_NAME VARCHAR(30), 
@EMAIL_ID VARCHAR(30), 
@PHONE_NO VARCHAR(10),
@PASSWORD VARCHAR(15)
AS
BEGIN
INSERT INTO tbl_USER(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,EMAIL_ID,PHONE_NO,PASSWORD,CREATED_DATE) VALUES (NEXT VALUE FOR seq_USER_ID,@FIRST_NAME, @LAST_NAME, @USER_NAME, @EMAIL_ID, @PHONE_NO,@PASSWORD,GETDATE())
END;

--PROCEDURE TO VERIFY LOGIN IN USER TABLE--
CREATE PROCEDURE proc_USER_VERIFY  
@EMAIL_ID VARCHAR(30), 
@PASSWORD VARCHAR(15)
AS
BEGIN
IF EXISTS(SELECT EMAIL_ID,PASSWORD FROM tbl_USER WHERE EMAIL_ID = @EMAIL_ID AND PASSWORD = @PASSWORD) 
BEGIN
UPDATE tbl_USER SET LAST_LOGIN = GETDATE() WHERE EMAIL_ID = @EMAIL_ID  
PRINT 'LOGIN SUCCESFUL'
END
ELSE
PRINT 'INVALID EMAILID/PASSWORD LOGIN UNSUCCESSFUL'
END;

--PROCEDURE TO UPDATE PASSWORD IN USER TABLE--
CREATE PROCEDURE proc_USER_UPDATE_PASSWORD
@EMAIL_ID VARCHAR(30), 
@PASSWORD VARCHAR(15)
AS
BEGIN
UPDATE tbl_USER SET PASSWORD=@PASSWORD, LAST_MODIFIED= GETDATE() WHERE EMAIL_ID=@EMAIL_ID; 
END;

--EXECUTING PROCEDURES--
EXECUTE [DBO].[proc_USER_CREATE]
@FIRST_NAME = 'SHRUTHI',
@LAST_NAME = 'PANEERSELVAM',
@USER_NAME = 'SHRUTHI233', 
@EMAIL_ID = 'shrutzz.shruu@gmail.com',
@PHONE_NO = '9655472337',
@PASSWORD = 'shUZZtshruthi';

EXECUTE [DBO].[proc_USER_UPDATE_PASSWORD]
@EMAIL_ID = 'shrutzz.shruu@gmail.com',
@PASSWORD = 'shruZZtshrUs76';

EXECUTE [DBO].[proc_USER_VERIFY]
@EMAIL_ID = 'shrutzz.shruu@gmail.com',
@PASSWORD = 'shruZZtshrUs76';

--DISPLAY USER TABLE--
SELECT * FROM tbl_USER;